### ISSUE TITLE
[PROPOSAL] Combine gems, extract opensearch-aws-sigv4

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-ruby#133]
### What are you proposing?

There are 5 gems in this repo:

- opensearch-api
- opensearch-dsl
- opensearch-ruby
- opensearch-aws-sigv4
- opensearch-transport

All except `opensearch-aws-sigv4` are always used by anyone wanting to call OpenSearch in Ruby.

- Propose to merge them into opensearch-ruby.
- Propose to extract opensearch-aws-sigv4 into a separate repo.

### What users have asked for this feature?

Coming from #127.  

### What problems are you trying to solve?

- I don't believe anyone ever uses opensearch-api, opensearch-dsl, opensearch-transport separately from opensearch-ruby. Seems like unnecessary overhead. 
- We have tags such as opensearch-api/2.1.2 and the number of tags will grow fast. Each tag only refers to a subset of the code, and may incorrectly imply some relationship between, say opensearch-ruby and opensearch-api in the tag. Theoretically they could even be incompatible.
- Our 1.x, 2.x branching strategy forces to release all the gems at the same time or create more confusion.

### What is the developer experience going to be?

Major increment opensearch-ruby and collapse the other 3 gems into it.

Extract code for opensearch-aws-sigv4 into a new repo called opensearch-ruby-aws-sigv4.

**Comment by nhtruong** [comment]
Should we keep `opensearch-dsl` separated in its own repo too? It's a supplemental gem to build queries. It's not always required, esp when the user want to build a micro-service to monitor a cluster for example.

**Comment by dblock** [comment]
Do we know if anyone is using opensearch-dsl separately?

**Comment by nhtruong** [comment]
One of the applications I worked in the past didn't use `dsl` (I built an ORM framework specialized for domain instead).
And yes it's to save space for micro-services that don't use `dsl`.

**Comment by dblock** [comment]
I don't have any strong opinions if you think it's useful!

**Comment by nhtruong** [comment]
@dblock Would you mind creating `opensearch-ruby-dsl` and `opensearch-ruby-aws-sigv4` repos?

**Comment by nhtruong** [comment]
@dblock discussed with @vamshin regarding [dsl-py](https://github.com/opensearch-project/opensearch-dsl-py) where we've merged it into the Python client instead of maintaining it as a standalone package like we planned to above. @vamshin brought up a valid point that addresses my micro-service concern: The footprint of the DSL library is minuscule. So, to reduce the overhead of maintaining another repo and keep it consistent with other clients, let's merge the DSL gem into the Ruby Client gem as well.

**Comment by RuslanHassonov** [comment]
Hi there, just a quick question: am I correct to assume that the merge hasn't been completed yet?

**Comment by nhtruong** [comment]
@RuslanHassonov sorry I missed this. It's a WIP and almost done #175
