### ISSUE TITLE
[Testing Confirmation] Confirm current testing requirements

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/opensearch-ruby#148]
As part of the discussion around implementing an organization-wide testing policy, I am visiting each repo to see what tests they currently perform. I am conducting this work on GitHub so that it is easy to reference. 

Looking at the OpenSearch Ruby repository, it appears there is 

| Repository  | Unit Tests | Integration Tests | Backwards Compatibility Tests | Additional Tests | Link | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
| OpenSearch Ruby | <li>- [x] </li> | <li>- [x] </li> | <li>- [ ] </li> | Link Checker, License Headers, Publish Docs  | https://github.com/opensearch-project/opensearch-ruby/issues/148 | 

I don't see any requirements for code coverage in the testing documentation. If there are any specific requirements could you respond to this issue to let me know? 

If there are any tests I missed or anything you think all repositories in OpenSearch should have for testing please respond to this issue with details.

**Comment by nhtruong** [comment]
@scrawfor99 The backward compatibility tests can be found in this workflow here: https://github.com/opensearch-project/opensearch-ruby/blob/main/.github/workflows/compatibility.yml

**Comment by VachaShah** [comment]
Hi @scrawfor99, clients test compatibility with multiple versions of OpenSearch.
