### ISSUE TITLE
[BUG] Point in time does not work

### ISSUE THREAD

**Issue by Jakob3xD** [opensearch-project/opensearch-ruby#156]
### What is the bug?
The lib tries to make request to `_pit` which is wrong and ends in a 400 from opensearch.

### How can one reproduce the bug?
Use the lib with PIT against Opensearch 2.6.0 

### What is the expected behavior?
The lib should use `_search/point_in_time` and not `_pit`

### What is your host/environment?
Openearch 2.6.0

**Comment by nhtruong** [comment]
This PR will handle this: https://github.com/opensearch-project/opensearch-ruby/pull/155

**Comment by nhtruong** [comment]
Said PR has been merged.
Check this guide to see how to use the new point-in-time:
https://github.com/opensearch-project/opensearch-ruby/blob/main/guides/search.md#pagination-with-point-in-time
