### ISSUE TITLE
Push 2.2.0 release to rubygems mirror

### ISSUE THREAD

**Issue by Jakob3xD** [opensearch-project/opensearch-ruby#167]
### What is the bug?
Version v2.2.0 got released two weeks ago but it is still missing on the gem mirror.
https://rubygems.org/gems/opensearch-ruby/versions/2.1.0 The latest version is 2.1.0

### What is the expected behavior?
There should be a v2.2.0 on the mirror.
https://rubygems.org/gems/opensearch-ruby/versions/2.2.0

**Comment by gaiksaya** [comment]
I do not see any tag for 2.2.0 related to opensearch-ruby https://github.com/opensearch-project/opensearch-ruby/tags
Also changelog is pointing to 2.1.0 https://github.com/opensearch-project/opensearch-ruby/blob/main/opensearch-ruby/CHANGELOG.md @dblock

**Comment by VachaShah** [comment]
From the releases section, looks like [opensearch-api](https://github.com/opensearch-project/opensearch-ruby/releases/tag/opensearch-api%2F2.2.0) gem was released for 2.2.0 which is available on ruby gems - https://rubygems.org/gems/opensearch-api

**Comment by Jakob3xD** [comment]
Ah sorry, I overlooked that it was an opensearch-api release. Everything works as expected.

**Comment by dblock** [comment]
Note that we have https://github.com/opensearch-project/opensearch-ruby/issues/133 discussing merging/splitting to avoid this kind of confusion.
