### ISSUE TITLE
[FEATURE] Create opensearch security API 

### ISSUE THREAD

**Issue by MarrakchiAyoub** [opensearch-project/opensearch-ruby#171]
### Is your feature request related to a problem?
 OpenSearch client does not have security APIs

### What solution would you like?
  write an architecture similar to elasticsearch-ruby >=8 witcch have the API needed to send opensearch security requests (create user, create role...)

**Comment by wbeckler** [comment]
This sounds like a great idea! Do you want to suggest an interface?
