### ISSUE TITLE
[FEATURE] Release v. Next

### ISSUE THREAD

**Issue by PussInDasBoot** [opensearch-project/opensearch-ruby#195]
Can the latest release (3.0) please be published to rubygems.org? The latest available release on rubygems.org is 2.1, which is two releases behind (also missing 2.2). Thank you!

**Comment by nhtruong** [comment]
We're working on on releasing `opensearch-ruby` 3.0.0. We've been dealing with on some CICD issues.

And 2.2.0 you're referring to was actually for `opensearch-api` https://rubygems.org/gems/opensearch-api/versions/2.2.0

**Comment by nhtruong** [comment]
We're facing with an issue from rubygems.org. We've opened a ticket with them and will keep you posted.

**Comment by nhtruong** [comment]
Waiting on this one https://github.com/opensearch-project/opensearch-ruby/pull/199

**Comment by nhtruong** [comment]
https://github.com/opensearch-project/opensearch-ruby/releases/tag/3.0.0 has been released: https://rubygems.org/gems/opensearch-ruby/versions/3.0.0
