### ISSUE TITLE
Please create additional "good first issues" to reach the suggested minimum of 15 by 9/15

### ISSUE THREAD

**Issue by rednaksi91** [opensearch-project/opensearch-ruby#198]
Open Source Contributor Initiative (OSCI) launches on September 20th. Java client repo lacks the minimum of 15 "good first issues" that can be picked up by participants of OSCI.

Please create additional "good first issues" to reach the suggested minimum of 15 by 9/15.

**Comment by dblock** [comment]
This is the Ruby client, not the Java client ;)

**Comment by nhtruong** [comment]
We won't be able to produce 15 Good first issues for a repo of this size. It makes sense for Core or Dashboard where we have multiple people managing 1 repo. With these clients repos, it's the opposite, we have one person managing multiple repos. So, It's several magnitudes smaller. I think 2 to 5 Good first issues make more sense for these repos.

**Comment by nhtruong** [comment]
https://github.com/opensearch-project/opensearch-ruby/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
