### ISSUE TITLE
[BUG] uninitialized constant OpenSearch::Transport::Transport::HTTP::Faraday::VERSION

### ISSUE THREAD

**Issue by kwent** [opensearch-project/opensearch-ruby#205]
### What is the bug?

Seeing 

```
uninitialized constant OpenSearch::Transport::Transport::HTTP::Faraday::VERSION
```

with `opensearch-ruby`, `3.0.0`

### How can one reproduce the bug?

Upgrade

### What is the expected behavior?

Not raising this exception.

### What is your host/environment?

3.0.0

### Do you have any screenshots?

N/A

### Do you have any additional context?

Crashed in non-app: opensearch-ruby (3.0.0) `lib/opensearch/transport/transport/http/faraday.rb` in `user_agent_header`

**Comment by Earlopain** [comment]
Doing a manual require of "opensearch/version" makes the error go away.

**Comment by Kiran9856** [comment]
Is there any work around for this issue ? Can we make fluent-plugin-opensearch plugin to use specific version of opensearch-ruby through config ?

**Comment by schinery** [comment]
> Doing a manual require of "opensearch/version" makes the error go away.

This workaround worked for me. Thanks for sharing 👍🏻

**Comment by paraiso-angelojohn** [comment]
> Is there any work around for this issue ? Can we make fluent-plugin-opensearch plugin to use specific version of opensearch-ruby through config ?

Sharing here my temporary workaround - create a Gemfile containing the known working versions of gems before opensearch-ruby-3.0.0 has been released.

```
source 'https://rubygems.org'
gem 'multi_json', '1.15.0'
gem 'faraday-retry', '1.0.3'
gem 'faraday-rack', '1.0.0'
gem 'faraday-patron', '1.0.0'
gem 'faraday-net_http_persistent', '1.2.0'
gem 'faraday-net_http', '1.0.1'
gem 'multipart-post', '2.3.0'
gem 'faraday-multipart', '1.0.4'
gem 'faraday-httpclient', '1.0.1'
gem 'faraday-excon', '1.1.0'
gem 'faraday-em_synchrony', '1.0.0'
gem 'faraday-em_http', '1.0.0'
gem 'faraday', '1.10.3'
gem 'opensearch-transport', '2.1.0'
gem 'opensearch-api', '2.2.0'
gem 'opensearch-ruby', '2.1.0'
gem 'aws-eventstream', '1.2.0'
gem 'aws-sigv4', '1.6.0'
gem 'faraday_middleware-aws-sigv4', '0.6.1'
gem 'excon', '0.100.0'
gem 'jmespath', '1.6.2'
gem 'aws-partitions', '1.793.0'
gem 'aws-sdk-core', '3.180.0'
```

**Comment by nhtruong** [comment]
Version 3.0.1 has been released with the fix for this issue. Please let us know if the problem has been resolved so we can close this ticket.

**Comment by Earlopain** [comment]
The new version fixes it. I'm able to use the current version of the gem without workarounds in my application now.

**Comment by nhtruong** [comment]
Yay! Closing this now.
