### ISSUE TITLE
Remove dangling x-pack references

### ISSUE THREAD

**Issue by jayeshathila** [opensearch-project/opensearch-ruby#22]
**What is the bug?**
As we don't use `x-pack` in opensearch we need to remove all the references of x-pack from codebase (which includes tests and templates)

**How can one reproduce the bug?**
1. Open Rubymine/Intellij
2. Find for `x-pack` / `xpack` reference in the code base
3. Logically remove the reference and fix the codebase accordingaly
4. Make the CI pass 

**What is the expected behavior?**
No reference to x-pack in the repo

**Comment by VijayanB** [comment]
Removed all generator code and created new issue to refactor and add it back that only generates opensearch api here #35
