### ISSUE TITLE
publish to rubygems.org repository

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-ruby#23]
Created github issue to track this: https://github.com/opensearch-project/opensearch-build/issues/872

**Comment by ccdredzik** [comment]
Hello. Any news on when will those packages become available for use through rubygems?

**Comment by cosmo0920** [comment]
FYI: It seems that this repository heavily based on the original Elastic's ruby client.
And I read this repository also provides _Rakefile_ that is Ruby style of makefile.
This file can handle rubygems release process. I'm not sure you all don't use this file and ignoring.
Almost Rubyists are willing to use this sophisticated way.
But this comment is just my two cents.
Thanks for your read.

Best,

Hiroshi

**Comment by VijayanB** [comment]
We released [1.0.0](https://github.com/opensearch-project/opensearch-ruby/releases/tag/v1.0.0)
Please create issues if you find any bug or for new feature request.
