### ISSUE TITLE
[FEATURE] Release 3.2.0 on rubygems

### ISSUE THREAD

**Issue by danielchenfigma** [opensearch-project/opensearch-ruby#232]
### Is your feature request related to a problem?
Want to start using the search_pipeline parameter

### What solution would you like?
Release 3.2.0 on rubygems

### What alternatives have you considered?
Patching 3.1.0

**Comment by quangcap** [comment]
Hi, any update on this? I also want to start using the search_pipeline parameter.

**Comment by quangcap** [comment]
The release pipeline was triggered but failed: https://build.ci.opensearch.org/job/opensearch-ruby-gems-release/31/
@nhtruong Hi can you help us with this?

**Comment by nhtruong** [comment]
@quangcap Sorry about that. Waiting for [this](https://github.com/opensearch-project/opensearch-ruby/pull/235) to merged and I'll retrigger the release.

**Comment by nhtruong** [comment]
blocked by https://github.com/opensearch-project/opensearch-ruby/issues/238

**Comment by nhtruong** [comment]
3.2.0 has been released: https://rubygems.org/gems/opensearch-ruby/versions/3.2.0
