### ISSUE TITLE
Cleanup unused branches

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-ruby#252]
Coming from https://github.com/opensearch-project/opensearch-clients/issues/64, cleanup unused branches.

For some unused branches we probably want to save state, so maybe note the last revision of any branch being deleted in this issue as it's being closed.

**Comment by dblock** [comment]
@nhtruong work with @opensearch-project/admin

**Comment by nhtruong** [comment]
@gaiksaya, would you mind delete the branches mentioned in this [comment](https://github.com/opensearch-project/opensearch-ruby/issues/252#issuecomment-2135508222) for this repo? Thank you.

**Comment by gaiksaya** [comment]
Above branches have been deleted. Thanks @nhtruong for the 2PR.
