### ISSUE TITLE
[PROPOSAL] Add USER_GUIDE

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/opensearch-ruby#61]
## What kind of business use case are you trying to solve? What are your requirements?

Ease of interaction and information rich documentation. I need to know what methods are available to a client instance without having to know how the code is structured (forgive my ignorance there - I'm a user, not a developer - the folder hierarchy of ruby modules is a little foreign to me) 

**What is the problem? What is preventing you from meeting the requirements?**

There's a number of methods that dont' have usage examples in the readme (index.exists was the first one I noticed). I would love to have a method reference for the functional parts of the client object (client.indices / client.cluster / client everything) 

**What are you proposing? What do you suggest we do to solve the problem or improve the existing situation?**

Ideally, every method available should have a usage example - I had to browse source code and dump a lot of objects before I found the things it was capable of that weren't in the usage examples in README. A list would be nice and the named arguments they take would be nice. 

**What are your assumptions or prerequisites?**

Assuming someone wants to use the ruby opensearch client and needs to know what it can and cannot do. 

**What are remaining open questions?**

List questions that may need to be answered before proceeding with an implementation.

**Comment by wbeckler** [comment]
I propose the next step would be a comprehensive method directory, maybe lacking examples, but at least including method signatures and explanation of the functionality. This should be done via a document generator off the code.

**Comment by dblock** [comment]
We've been adding user guides in other clients, e.g. https://github.com/opensearch-project/opensearch-py/blob/main/USER_GUIDE.md, let's do the same here?
