### ISSUE TITLE
Release opensearch-transport updates with Faraday 2 support

### ISSUE THREAD

**Issue by BrianHawley** [opensearch-project/opensearch-ruby#91]
### Is your feature request related to a problem?
#59 is fixed, but not released.

### What solution would you like?
Release opensearch-transport 1.0.1 and 2.0.1.

### Do you have any additional context?
Can the opensearch gem's version restriction for opensearch-transport be changed from `"2.0.0"` and `"1.0.0"`, to `"~> 2.0.0"` and `"~> 1.0.0"`, respectively? It probably doesn't need to be more specific, but if it does, then change it to `"2.0.1"` and `"1.0.1"` respectively.

**Comment by BrianHawley** [comment]
@dblock as requested.

**Comment by BrianHawley** [comment]
@VachaShah do you know who to tag here? Should I make PRs?

**Comment by dblock** [comment]
@bbarani 

I believe the workflow is not automated. Something about login to rubygems/security keys ...

**Comment by VachaShah** [comment]
Apologies for a delayed response @BrianHawley! I will work on releasing opensearch-transport 1.0.1 and 2.0.1.

**Comment by VachaShah** [comment]
Released opensearch-transport with Faraday updates

For 1.x line:
https://rubygems.org/gems/opensearch-transport/versions/1.0.1
https://rubygems.org/gems/opensearch-ruby/versions/1.0.1

For 2.x line:
https://rubygems.org/gems/opensearch-transport/versions/2.0.1
https://rubygems.org/gems/opensearch-ruby/versions/2.0.3
